/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.entities.Train;
import org.example.entities.User;
import org.example.services.UserBookingService;
import org.example.util.UserServiceUtil;

import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.format.DateTimeParseException;
import java.util.*;

public class App {

    public static void main(String[] args) {
        System.out.println("Running Train Booking System");
        Scanner sc = new Scanner(System.in);
        int option = 0;
        UserBookingService userBookingService;
        try{
            userBookingService = new UserBookingService();
        } catch (IOException e) {
            System.out.println("there is something wrong");
            return;
        }

        Train trainSelectedForBooking = new Train();
        String source = "";
        String destination = "";

        while(option!=7){
            System.out.println("Enter your choice");
            System.out.println("1. Sign up");
            System.out.println("2. Login");
            System.out.println("3. Fetch Bookings");
            System.out.println("4. Search Trains");
            System.out.println("5. Book a seat");
            System.out.println("6. Cancel my Booking");
            System.out.println("7. Exit");
            option = sc.nextInt();

            switch(option){
                case 1:
                    System.out.println("Enter your username");
                    String username = sc.next();
                    System.out.println("Enter your password");
                    String password = sc.next();
                    User user = new User(username, password,
                            UserServiceUtil.hashPassword(password),
                            new ArrayList<>(), UUID.randomUUID().toString().substring(0,8));
                    userBookingService.signUp(user);
                    break;

                case 2:
                    System.out.println("Enter your username");
                    String nameToLogin = sc.next();
                    System.out.println("Enter your password");
                    String passwordToLogin = sc.next();
                    User userToLogin = new User(nameToLogin, passwordToLogin,
                            UserServiceUtil.hashPassword(passwordToLogin),
                            new ArrayList<>(), UUID.randomUUID().toString());
                    try{
                        userBookingService = new UserBookingService(userToLogin);
                        boolean loggedIn = userBookingService.loginUser();
                        if (loggedIn) {
                            System.out.println("Login successful!");
                        } else {
                            System.out.println("Login failed! Invalid credentials.");
                        }
                    } catch (IOException e) {
                        return;
                    }
                    break;

                case 3:
                    System.out.println("Fetching your Bookings");
                    userBookingService.fetchBooking();
                    break;

                case 4:
                    System.out.println("Type your source station");
                    String sourceStation = sc.next();
                    System.out.println("Type your destination station");
                    String destinationStation = sc.next();
                    List<Train> trains = userBookingService.getTrains(sourceStation, destinationStation);
                    int index = 1;
                    for(Train train : trains){
                        System.out.println(index++ +" Train id : "+ train.getTrainId());
                        for(Map.Entry<String, String> entry: train.getStationTimes().entrySet()){
                            System.out.println("Station "+ entry.getKey()+" Time : "+ entry.getValue());
                        }
                    }
                    if(index == 1){
                        System.out.println("no train found!");
                    }else {
                        System.out.println("Select a train by typing 1,2,3...");
                        trainSelectedForBooking = trains.get(sc.nextInt());
                        source = sourceStation;
                        destination = destinationStation;
                    }
                    break;

                case 5:
                    sc.nextLine();
                    SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
                    System.out.println("Enter date of travel (DD-MM-YYYY): ");
                    String date = sc.nextLine();
                    Date travelDate = new Date();
                    try {
                        travelDate = formatter.parse(date);
                        Date today = new Date();
                        if(travelDate.before(today)){
                            System.out.println("Error: Travel date must be a future date.");
                        }
                    } catch (ParseException e) {
                        System.out.println("Invalid date format. Please use DD-MM-YYYY.");
                        break;
                    }

                    System.out.println("Select a seat out of these seats");
                    List<List<Integer>> seats = userBookingService.fetchSeats(trainSelectedForBooking);
                    for(List<Integer> seat : seats){
                        for(Integer i: seat){
                            System.out.print(i+" ");
                        }
                        System.out.println();
                    }
                    System.out.println("Select the seat by typing the row and column");
                    System.out.println("Enter the row (starting from 0)");
                    int row = sc.nextInt();
                    System.out.println("Enter the column (starting from 0)");
                    int col = sc.nextInt();
                    System.out.println("Booking your seat....");
                    Boolean booked = userBookingService.bookTrainSeat(trainSelectedForBooking, row, col, source, destination, travelDate);
                    if(booked.equals(Boolean.TRUE)){
                        System.out.println("Booked! Enjoy your journey");
                    }else{
                        System.out.println("Can't book this seat");
                    }
                    break;

                case 6:
                    sc.nextLine();
                    System.out.println("fetching user bookings :");
                    userBookingService.fetchBooking();
                    System.out.println("Enter ticket Id for cancellation :");
                    String cancel =  sc.nextLine();
                    try {
                        if(userBookingService.cancelBooking(cancel)){
                            System.out.println("Booking has been cancelled");
                        }else {
                            System.out.println("Can't cancel this seat");
                        }
                    }
                    catch (IOException e){
                        System.out.println("Error while cancelling this seat");
                    }
                    break;

                default:
                    break;

            }
        }
    }
}
