/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.classes.Person;
import org.example.classes.man;
import org.example.classes.personInvocationHandler;

import java.lang.reflect.Proxy;


public class App {
    public static void main(String[] args){
        man mohan = new man("mohan", 30, "delhi", "India");
        ClassLoader mohanClassLoader = mohan.getClass().getClassLoader();

        Class[] interfaces = mohan.getClass().getInterfaces();
        Person proxyMohan = (Person) Proxy.newProxyInstance(mohanClassLoader, interfaces, new personInvocationHandler(mohan));
        proxyMohan.introduce(mohan.getName());
    }
}
